:-encoding(utf8).

consonant('b').
consonant('c').
consonant('ç').
consonant('d').
consonant('f').
consonant('g').
consonant('ğ').
consonant('h').
consonant('j').
consonant('k').
consonant('l').
consonant('m').
consonant('n').
consonant('p').
consonant('r').
consonant('s').
consonant('ş').
consonant('t').
consonant('v').
consonant('y').
consonant('z').
